
 # Makefile
 
 #  Created on: 6 Apr 2020
 #      Author: Gabriel Maquignaz & Maxime P. Poffet
 

# Define project name here
PROJECT = Dancer

#Define path to the e-puck2_main-processor folder
GLOBAL_PATH = ../../lib/e-puck2_main-processor

#Source files to include
CSRC += ./main.c \
		./trajectory.c \
		./vision.c \
		./sound.c \
		./user_button.c \
		./blinking_leds.c \
		

#Header folders to include
INCDIR += 

#Jump to the main Makefile
include $(GLOBAL_PATH)/Makefile